select *
from OPINIE;

SELECT COUNT(*) 
FROM OPINIE;

SELECT * FROM OPINIE FETCH FIRST 5 ROWS ONLY;

SELECT COUNT(*) AS LICZBA_OPINII
FROM OPINIE;

SELECT TEXT, SENTIMENT
FROM OPINIE
WHERE SENTIMENT = 'Positive';

SELECT TEXT, CONFIDENCE_SCORE
FROM OPINIE
ORDER BY CONFIDENCE_SCORE DESC;

SELECT SENTIMENT, COUNT(*) AS ILE
FROM OPINIE
GROUP BY SENTIMENT;

SELECT DISTINCT SOURCE
FROM OPINIE;

SELECT DISTINCT LOCATION
FROM OPINIE;

SELECT TEXT, CONFIDENCE_SCORE
FROM OPINIE
WHERE SENTIMENT = 'Positive'
ORDER BY CONFIDENCE_SCORE DESC
FETCH FIRST 5 ROWS ONLY;

SELECT TEXT
FROM OPINIE
WHERE LOWER(TEXT) LIKE '%bad%';

SELECT
  MIN(CONFIDENCE_SCORE) AS MIN_CONF,
  MAX(CONFIDENCE_SCORE) AS MAX_CONF
FROM OPINIE;

SELECT
  TRUNC(CREATED_AT) AS DATA,
  COUNT(*) AS ILE
FROM OPINIE
GROUP BY TRUNC(CREATED_AT)
ORDER BY DATA;

